Repository cockpit-project/cockpit-podman, pull requests merged in 2020-08, with the labels that each got.

#490 Update translations from Fedora Weblate
  po/sk.po
Labels: bot

#491 Add actions for Pods
  lib/table.css
  src/Containers.jsx
  src/PodActions.jsx
  src/client.js
  src/util.js
  test/check-application
Labels: release-note

#501 Refresh translations from weblate
  po/cs.po
  po/de.po
  po/es.po
  po/fr.po
  po/pl.po
  po/pt_BR.po
  po/pt_PT.po
  po/sk.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
Labels: bot

#506 package.json: Update throttle-debounce package dependency
  package.json
Labels: bot

#508 Update translations from Fedora Weblate
  po/cs.po
  po/de.po
  po/es.po
  po/fr.po
  po/pl.po
  po/pt_BR.po
  po/pt_PT.po
  po/sk.po
  po/tr.po
  po/uk.po
  po/zh_CN.po
Labels: bot

#509 package.json: Update @patternfly/react-core package dependency
  package.json
Labels: bot

#512 cockpituous: Release to Fedora 33
  cockpituous-release
Labels: no-test

#521 package.json: Update @patternfly/react-core package dependency
  package.json
Labels: bot

#523 Update translations from Fedora Weblate
  po/fr.po
  po/pt_BR.po
Labels: bot
