Repository cockpit-project/cockpit-podman, pull requests merged in 2020-07, with the labels that each got.

#420 package.json: Update xterm package dependency
  package.json
Labels: bot

#426 [rhel8] metainfo: Fix launchable and update description
  org.cockpit-project.podman.metainfo.xml
Labels: backport

#434 package.json: Update xterm package dependency
  package.json
Labels: bot

#461 If container does not have tty, 'exec' and then connect
  src/ContainerTerminal.jsx
  src/Containers.jsx
  src/client.js
  test/check-application
Labels: release-note

#467 Enable untagging images
  src/ImageDeleteModal.jsx
  src/Images.css
  src/Images.jsx
  src/client.js
  test/check-application
Labels: release-note

#470 test: Adjust checkpoint tests for debian-testing
  test/check-application
Labels: needswork
