Repository cockpit-project/cockpit-podman, pull requests merged in 2022-07, with the labels that each got.

#1030 .github: don't depend on COCKPIT_REPO_STAMP target
  .github/workflows/reposchutz.yml
Labels: no-test

#1045 test: Fix pgrep invocation
  test/check-application
Labels: release-blocker

#1041 Fix system logic in prune unused images dialog
  src/PruneUnusedImagesModal.jsx
  test/check-application
Labels: release-blocker

#1046 fmf: Add non-git fallback for npm module installation
  test/browser/run-test.sh
Labels: no-test, release-blocker

#1050 test: Adjust for ubuntu-stable moving to 22.10 "kinetic"
  test/check-application
Labels: no-test

#1053 Makefile: Use rsync-friendly directory path
  Makefile
Labels: no-test
