Repository cockpit-project/cockpit-podman, pull requests merged in 2022-05, with the labels that each got.

#974 packit: Fix copr owner
  packit.yaml
Labels: release-blocker

#966 container rename support
  src/ContainerRenameModal.jsx
  src/Containers.jsx
  src/app.jsx
  src/client.js
  test/check-application
Labels: release-note

#1000 .github: drop deploy-keys.sh
  .github/deploy-keys.sh
Labels: blocked
