Repository cockpit-project/cockpit-podman, pull requests merged in 2022-06, with the labels that each got.

#1011 Pick up cockpit test API fix for Firefox 101
  Makefile
Labels: release-blocker

#1009 workflows: Tag our releases in node-cache
  .github/workflows/release.yml
Labels: release-blocker

#1013 Re-drop node_modules from release tarballs, Include Cockpit repo files in release tarballs
  Makefile
Labels: release-blocker

#1014 packit: Drop FMF hack, enable downstream job notifications
  packit.yaml
Labels: no-test, release-blocker

#1020 .github: add reposchutz workflow
  .github/workflows/reposchutz.yml
Labels: no-test
