Repository cockpit-project/cockpit-podman, pull requests merged in 2023-10, with the labels that each got.

#1430 .github: drop npm-update workflows
  .github/workflows/npm-update-pf.yml
  .github/workflows/npm-update.yml
Labels: no-test, .github-changes

#1447 React to health_status events
  src/app.jsx
Labels: release-blocker

#1356 test: Add hack to avoid losing focus on #containers-filter
  test/check-application
Labels: flake

#1446 dependabot: Run in our evenings, reduce limit
  .github/dependabot.yml
Labels: no-test, .github-changes

#1452 Don't crash when image is being downloaded and integration/console tab is clicked
  src/Containers.jsx
  src/ImageRunModal.jsx
Labels: release-blocker
