Repository cockpit-project/cockpit-podman, pull requests merged in 2023-07, with the labels that each got.

#1328 test: bump reference-image to Fedora-38
  test/reference-image
Labels: no-test

#1330 fmf: Retry pulling container images
  test/browser/browser.sh
Labels: no-test, flake

#1329 Don't re-fetch all containers for "cleanup" event
  src/app.jsx
Labels: flake

#1352 Drop leftover debugging console log
  src/app.jsx
Labels: release-blocker

#1357 fix: Screen width for podman containers
  src/Containers.scss
  src/podman.scss
Labels: needswork

#1345 Show time of container's checkpoint, if any is present
  src/ContainerDetails.jsx
  test/check-application
Labels: release-note

#1365 packit: Build COPR for main commits
  packit.yaml
Labels: no-test
