Repository cockpit-project/cockpit-podman, pull requests merged in 2024-05, with the labels that each got.

#1713 test: Adjust expected error message for port conflict to podman 5.0.2
  test/check-application
Labels: release-blocker

#1716 dependabot: Dial down to weekly
  .github/dependabot.yml
Labels: no-test, .github-changes

#1722 .eslintrc.json: boolean values are deprecated for globals
  .eslintrc.json
Labels: no-test
