Repository cockpit-project/cockpit-podman, pull requests merged in 2024-01, with the labels that each got.

#1525 test: Fix race condition with deleting busy intermediate image
  test/check-application
Labels: flake, release-blocker

#1533 test: Fix testHealthcheck table queries
  test/check-application
Labels: flake

#1541 .gitignore: improvements
  .gitignore
Labels: no-test

#1543 fmf: Fix installation of our main-builds COPR
  test/browser/browser.sh
Labels: no-test
